# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vincent/projet/groupe7

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vincent/projet/groupe7

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vincent/projet/groupe7/CMakeFiles /home/vincent/projet/groupe7/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vincent/projet/groupe7/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named kad

# Build rule for target.
kad: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kad
.PHONY : kad

# fast build rule for target.
kad/fast:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/build
.PHONY : kad/fast

Main.o: Main.c.o

.PHONY : Main.o

# target to build an object file
Main.c.o:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/Main.c.o
.PHONY : Main.c.o

Main.i: Main.c.i

.PHONY : Main.i

# target to preprocess a source file
Main.c.i:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/Main.c.i
.PHONY : Main.c.i

Main.s: Main.c.s

.PHONY : Main.s

# target to generate assembly for a file
Main.c.s:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/Main.c.s
.PHONY : Main.c.s

event/lisent.o: event/lisent.c.o

.PHONY : event/lisent.o

# target to build an object file
event/lisent.c.o:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/event/lisent.c.o
.PHONY : event/lisent.c.o

event/lisent.i: event/lisent.c.i

.PHONY : event/lisent.i

# target to preprocess a source file
event/lisent.c.i:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/event/lisent.c.i
.PHONY : event/lisent.c.i

event/lisent.s: event/lisent.c.s

.PHONY : event/lisent.s

# target to generate assembly for a file
event/lisent.c.s:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/event/lisent.c.s
.PHONY : event/lisent.c.s

lib/sqlite3.o: lib/sqlite3.c.o

.PHONY : lib/sqlite3.o

# target to build an object file
lib/sqlite3.c.o:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/lib/sqlite3.c.o
.PHONY : lib/sqlite3.c.o

lib/sqlite3.i: lib/sqlite3.c.i

.PHONY : lib/sqlite3.i

# target to preprocess a source file
lib/sqlite3.c.i:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/lib/sqlite3.c.i
.PHONY : lib/sqlite3.c.i

lib/sqlite3.s: lib/sqlite3.c.s

.PHONY : lib/sqlite3.s

# target to generate assembly for a file
lib/sqlite3.c.s:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/lib/sqlite3.c.s
.PHONY : lib/sqlite3.c.s

package/SendFileTCP.o: package/SendFileTCP.c.o

.PHONY : package/SendFileTCP.o

# target to build an object file
package/SendFileTCP.c.o:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/package/SendFileTCP.c.o
.PHONY : package/SendFileTCP.c.o

package/SendFileTCP.i: package/SendFileTCP.c.i

.PHONY : package/SendFileTCP.i

# target to preprocess a source file
package/SendFileTCP.c.i:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/package/SendFileTCP.c.i
.PHONY : package/SendFileTCP.c.i

package/SendFileTCP.s: package/SendFileTCP.c.s

.PHONY : package/SendFileTCP.s

# target to generate assembly for a file
package/SendFileTCP.c.s:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/package/SendFileTCP.c.s
.PHONY : package/SendFileTCP.c.s

package/bdd.o: package/bdd.c.o

.PHONY : package/bdd.o

# target to build an object file
package/bdd.c.o:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/package/bdd.c.o
.PHONY : package/bdd.c.o

package/bdd.i: package/bdd.c.i

.PHONY : package/bdd.i

# target to preprocess a source file
package/bdd.c.i:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/package/bdd.c.i
.PHONY : package/bdd.c.i

package/bdd.s: package/bdd.c.s

.PHONY : package/bdd.s

# target to generate assembly for a file
package/bdd.c.s:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/package/bdd.c.s
.PHONY : package/bdd.c.s

package/bukket.o: package/bukket.c.o

.PHONY : package/bukket.o

# target to build an object file
package/bukket.c.o:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/package/bukket.c.o
.PHONY : package/bukket.c.o

package/bukket.i: package/bukket.c.i

.PHONY : package/bukket.i

# target to preprocess a source file
package/bukket.c.i:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/package/bukket.c.i
.PHONY : package/bukket.c.i

package/bukket.s: package/bukket.c.s

.PHONY : package/bukket.s

# target to generate assembly for a file
package/bukket.c.s:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/package/bukket.c.s
.PHONY : package/bukket.c.s

package/connexion_reseau.o: package/connexion_reseau.c.o

.PHONY : package/connexion_reseau.o

# target to build an object file
package/connexion_reseau.c.o:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/package/connexion_reseau.c.o
.PHONY : package/connexion_reseau.c.o

package/connexion_reseau.i: package/connexion_reseau.c.i

.PHONY : package/connexion_reseau.i

# target to preprocess a source file
package/connexion_reseau.c.i:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/package/connexion_reseau.c.i
.PHONY : package/connexion_reseau.c.i

package/connexion_reseau.s: package/connexion_reseau.c.s

.PHONY : package/connexion_reseau.s

# target to generate assembly for a file
package/connexion_reseau.c.s:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/package/connexion_reseau.c.s
.PHONY : package/connexion_reseau.c.s

package/fichier.o: package/fichier.c.o

.PHONY : package/fichier.o

# target to build an object file
package/fichier.c.o:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/package/fichier.c.o
.PHONY : package/fichier.c.o

package/fichier.i: package/fichier.c.i

.PHONY : package/fichier.i

# target to preprocess a source file
package/fichier.c.i:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/package/fichier.c.i
.PHONY : package/fichier.c.i

package/fichier.s: package/fichier.c.s

.PHONY : package/fichier.s

# target to generate assembly for a file
package/fichier.c.s:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/package/fichier.c.s
.PHONY : package/fichier.c.s

package/find_node.o: package/find_node.c.o

.PHONY : package/find_node.o

# target to build an object file
package/find_node.c.o:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/package/find_node.c.o
.PHONY : package/find_node.c.o

package/find_node.i: package/find_node.c.i

.PHONY : package/find_node.i

# target to preprocess a source file
package/find_node.c.i:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/package/find_node.c.i
.PHONY : package/find_node.c.i

package/find_node.s: package/find_node.c.s

.PHONY : package/find_node.s

# target to generate assembly for a file
package/find_node.c.s:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/package/find_node.c.s
.PHONY : package/find_node.c.s

package/find_value.o: package/find_value.c.o

.PHONY : package/find_value.o

# target to build an object file
package/find_value.c.o:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/package/find_value.c.o
.PHONY : package/find_value.c.o

package/find_value.i: package/find_value.c.i

.PHONY : package/find_value.i

# target to preprocess a source file
package/find_value.c.i:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/package/find_value.c.i
.PHONY : package/find_value.c.i

package/find_value.s: package/find_value.c.s

.PHONY : package/find_value.s

# target to generate assembly for a file
package/find_value.c.s:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/package/find_value.c.s
.PHONY : package/find_value.c.s

package/node.o: package/node.c.o

.PHONY : package/node.o

# target to build an object file
package/node.c.o:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/package/node.c.o
.PHONY : package/node.c.o

package/node.i: package/node.c.i

.PHONY : package/node.i

# target to preprocess a source file
package/node.c.i:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/package/node.c.i
.PHONY : package/node.c.i

package/node.s: package/node.c.s

.PHONY : package/node.s

# target to generate assembly for a file
package/node.c.s:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/package/node.c.s
.PHONY : package/node.c.s

package/ping.o: package/ping.c.o

.PHONY : package/ping.o

# target to build an object file
package/ping.c.o:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/package/ping.c.o
.PHONY : package/ping.c.o

package/ping.i: package/ping.c.i

.PHONY : package/ping.i

# target to preprocess a source file
package/ping.c.i:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/package/ping.c.i
.PHONY : package/ping.c.i

package/ping.s: package/ping.c.s

.PHONY : package/ping.s

# target to generate assembly for a file
package/ping.c.s:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/package/ping.c.s
.PHONY : package/ping.c.s

package/publish_key.o: package/publish_key.c.o

.PHONY : package/publish_key.o

# target to build an object file
package/publish_key.c.o:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/package/publish_key.c.o
.PHONY : package/publish_key.c.o

package/publish_key.i: package/publish_key.c.i

.PHONY : package/publish_key.i

# target to preprocess a source file
package/publish_key.c.i:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/package/publish_key.c.i
.PHONY : package/publish_key.c.i

package/publish_key.s: package/publish_key.c.s

.PHONY : package/publish_key.s

# target to generate assembly for a file
package/publish_key.c.s:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/package/publish_key.c.s
.PHONY : package/publish_key.c.s

package/send_udp.o: package/send_udp.c.o

.PHONY : package/send_udp.o

# target to build an object file
package/send_udp.c.o:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/package/send_udp.c.o
.PHONY : package/send_udp.c.o

package/send_udp.i: package/send_udp.c.i

.PHONY : package/send_udp.i

# target to preprocess a source file
package/send_udp.c.i:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/package/send_udp.c.i
.PHONY : package/send_udp.c.i

package/send_udp.s: package/send_udp.c.s

.PHONY : package/send_udp.s

# target to generate assembly for a file
package/send_udp.c.s:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/package/send_udp.c.s
.PHONY : package/send_udp.c.s

package/store.o: package/store.c.o

.PHONY : package/store.o

# target to build an object file
package/store.c.o:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/package/store.c.o
.PHONY : package/store.c.o

package/store.i: package/store.c.i

.PHONY : package/store.i

# target to preprocess a source file
package/store.c.i:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/package/store.c.i
.PHONY : package/store.c.i

package/store.s: package/store.c.s

.PHONY : package/store.s

# target to generate assembly for a file
package/store.c.s:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/package/store.c.s
.PHONY : package/store.c.s

package/trouver_valeur.o: package/trouver_valeur.c.o

.PHONY : package/trouver_valeur.o

# target to build an object file
package/trouver_valeur.c.o:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/package/trouver_valeur.c.o
.PHONY : package/trouver_valeur.c.o

package/trouver_valeur.i: package/trouver_valeur.c.i

.PHONY : package/trouver_valeur.i

# target to preprocess a source file
package/trouver_valeur.c.i:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/package/trouver_valeur.c.i
.PHONY : package/trouver_valeur.c.i

package/trouver_valeur.s: package/trouver_valeur.c.s

.PHONY : package/trouver_valeur.s

# target to generate assembly for a file
package/trouver_valeur.c.s:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/package/trouver_valeur.c.s
.PHONY : package/trouver_valeur.c.s

utilitaires/TCP.o: utilitaires/TCP.c.o

.PHONY : utilitaires/TCP.o

# target to build an object file
utilitaires/TCP.c.o:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/utilitaires/TCP.c.o
.PHONY : utilitaires/TCP.c.o

utilitaires/TCP.i: utilitaires/TCP.c.i

.PHONY : utilitaires/TCP.i

# target to preprocess a source file
utilitaires/TCP.c.i:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/utilitaires/TCP.c.i
.PHONY : utilitaires/TCP.c.i

utilitaires/TCP.s: utilitaires/TCP.c.s

.PHONY : utilitaires/TCP.s

# target to generate assembly for a file
utilitaires/TCP.c.s:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/utilitaires/TCP.c.s
.PHONY : utilitaires/TCP.c.s

utilitaires/UDP.o: utilitaires/UDP.c.o

.PHONY : utilitaires/UDP.o

# target to build an object file
utilitaires/UDP.c.o:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/utilitaires/UDP.c.o
.PHONY : utilitaires/UDP.c.o

utilitaires/UDP.i: utilitaires/UDP.c.i

.PHONY : utilitaires/UDP.i

# target to preprocess a source file
utilitaires/UDP.c.i:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/utilitaires/UDP.c.i
.PHONY : utilitaires/UDP.c.i

utilitaires/UDP.s: utilitaires/UDP.c.s

.PHONY : utilitaires/UDP.s

# target to generate assembly for a file
utilitaires/UDP.c.s:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/utilitaires/UDP.c.s
.PHONY : utilitaires/UDP.c.s

utilitaires/console_color.o: utilitaires/console_color.c.o

.PHONY : utilitaires/console_color.o

# target to build an object file
utilitaires/console_color.c.o:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/utilitaires/console_color.c.o
.PHONY : utilitaires/console_color.c.o

utilitaires/console_color.i: utilitaires/console_color.c.i

.PHONY : utilitaires/console_color.i

# target to preprocess a source file
utilitaires/console_color.c.i:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/utilitaires/console_color.c.i
.PHONY : utilitaires/console_color.c.i

utilitaires/console_color.s: utilitaires/console_color.c.s

.PHONY : utilitaires/console_color.s

# target to generate assembly for a file
utilitaires/console_color.c.s:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/utilitaires/console_color.c.s
.PHONY : utilitaires/console_color.c.s

utilitaires/fileTabChar.o: utilitaires/fileTabChar.c.o

.PHONY : utilitaires/fileTabChar.o

# target to build an object file
utilitaires/fileTabChar.c.o:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/utilitaires/fileTabChar.c.o
.PHONY : utilitaires/fileTabChar.c.o

utilitaires/fileTabChar.i: utilitaires/fileTabChar.c.i

.PHONY : utilitaires/fileTabChar.i

# target to preprocess a source file
utilitaires/fileTabChar.c.i:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/utilitaires/fileTabChar.c.i
.PHONY : utilitaires/fileTabChar.c.i

utilitaires/fileTabChar.s: utilitaires/fileTabChar.c.s

.PHONY : utilitaires/fileTabChar.s

# target to generate assembly for a file
utilitaires/fileTabChar.c.s:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/utilitaires/fileTabChar.c.s
.PHONY : utilitaires/fileTabChar.c.s

utilitaires/hashFile.o: utilitaires/hashFile.c.o

.PHONY : utilitaires/hashFile.o

# target to build an object file
utilitaires/hashFile.c.o:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/utilitaires/hashFile.c.o
.PHONY : utilitaires/hashFile.c.o

utilitaires/hashFile.i: utilitaires/hashFile.c.i

.PHONY : utilitaires/hashFile.i

# target to preprocess a source file
utilitaires/hashFile.c.i:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/utilitaires/hashFile.c.i
.PHONY : utilitaires/hashFile.c.i

utilitaires/hashFile.s: utilitaires/hashFile.c.s

.PHONY : utilitaires/hashFile.s

# target to generate assembly for a file
utilitaires/hashFile.c.s:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/utilitaires/hashFile.c.s
.PHONY : utilitaires/hashFile.c.s

utilitaires/utilitaire.o: utilitaires/utilitaire.c.o

.PHONY : utilitaires/utilitaire.o

# target to build an object file
utilitaires/utilitaire.c.o:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/utilitaires/utilitaire.c.o
.PHONY : utilitaires/utilitaire.c.o

utilitaires/utilitaire.i: utilitaires/utilitaire.c.i

.PHONY : utilitaires/utilitaire.i

# target to preprocess a source file
utilitaires/utilitaire.c.i:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/utilitaires/utilitaire.c.i
.PHONY : utilitaires/utilitaire.c.i

utilitaires/utilitaire.s: utilitaires/utilitaire.c.s

.PHONY : utilitaires/utilitaire.s

# target to generate assembly for a file
utilitaires/utilitaire.c.s:
	$(MAKE) -f CMakeFiles/kad.dir/build.make CMakeFiles/kad.dir/utilitaires/utilitaire.c.s
.PHONY : utilitaires/utilitaire.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... kad"
	@echo "... Main.o"
	@echo "... Main.i"
	@echo "... Main.s"
	@echo "... event/lisent.o"
	@echo "... event/lisent.i"
	@echo "... event/lisent.s"
	@echo "... lib/sqlite3.o"
	@echo "... lib/sqlite3.i"
	@echo "... lib/sqlite3.s"
	@echo "... package/SendFileTCP.o"
	@echo "... package/SendFileTCP.i"
	@echo "... package/SendFileTCP.s"
	@echo "... package/bdd.o"
	@echo "... package/bdd.i"
	@echo "... package/bdd.s"
	@echo "... package/bukket.o"
	@echo "... package/bukket.i"
	@echo "... package/bukket.s"
	@echo "... package/connexion_reseau.o"
	@echo "... package/connexion_reseau.i"
	@echo "... package/connexion_reseau.s"
	@echo "... package/fichier.o"
	@echo "... package/fichier.i"
	@echo "... package/fichier.s"
	@echo "... package/find_node.o"
	@echo "... package/find_node.i"
	@echo "... package/find_node.s"
	@echo "... package/find_value.o"
	@echo "... package/find_value.i"
	@echo "... package/find_value.s"
	@echo "... package/node.o"
	@echo "... package/node.i"
	@echo "... package/node.s"
	@echo "... package/ping.o"
	@echo "... package/ping.i"
	@echo "... package/ping.s"
	@echo "... package/publish_key.o"
	@echo "... package/publish_key.i"
	@echo "... package/publish_key.s"
	@echo "... package/send_udp.o"
	@echo "... package/send_udp.i"
	@echo "... package/send_udp.s"
	@echo "... package/store.o"
	@echo "... package/store.i"
	@echo "... package/store.s"
	@echo "... package/trouver_valeur.o"
	@echo "... package/trouver_valeur.i"
	@echo "... package/trouver_valeur.s"
	@echo "... utilitaires/TCP.o"
	@echo "... utilitaires/TCP.i"
	@echo "... utilitaires/TCP.s"
	@echo "... utilitaires/UDP.o"
	@echo "... utilitaires/UDP.i"
	@echo "... utilitaires/UDP.s"
	@echo "... utilitaires/console_color.o"
	@echo "... utilitaires/console_color.i"
	@echo "... utilitaires/console_color.s"
	@echo "... utilitaires/fileTabChar.o"
	@echo "... utilitaires/fileTabChar.i"
	@echo "... utilitaires/fileTabChar.s"
	@echo "... utilitaires/hashFile.o"
	@echo "... utilitaires/hashFile.i"
	@echo "... utilitaires/hashFile.s"
	@echo "... utilitaires/utilitaire.o"
	@echo "... utilitaires/utilitaire.i"
	@echo "... utilitaires/utilitaire.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

